name: Main Pipeline

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SCORE_HUMANITEC_VERSION: 'latest'

jobs:

  build-frontend:
    uses: ./.github/workflows/build-service.yaml
    secrets: inherit
    with:
      service-name: frontend
      image-name: registry.humanitec.io/public/bank-demo-frontend
      HUMANITEC_ORG: ${{ vars.HUMANITEC_ORG }}

  build-moneyapi:
    uses: ./.github/workflows/build-service.yaml
    secrets: inherit
    with:
      service-name: money-api
      image-name: registry.humanitec.io/public/bank-demo-money-api
      HUMANITEC_ORG: ${{ vars.HUMANITEC_ORG }}

  build-usersapi:
    uses: ./.github/workflows/build-service.yaml
    secrets: inherit
    with:
      service-name: users-api
      image-name: registry.humanitec.io/public/bank-demo-users-api
      HUMANITEC_ORG: ${{ vars.HUMANITEC_ORG }}

  run-score:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-moneyapi, build-usersapi]

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        name: Check if score files have been updated
        id: changes
        with:
          filters: |
            scorefiles:
              - '**/score.yaml'
              - '**/humanitec.score.yaml'
      
      - name: install score-humanitec
        if: steps.changes.outputs.scorefiles == 'true'
        uses: score-spec/setup-score@v2
        with:
          file: score-humanitec
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.SCORE_HUMANITEC_VERSION }}

      - name: Run Score - Money API
        if: steps.changes.outputs.scorefiles == 'true'
        run: score-humanitec delta --retry --deploy --token ${{ secrets.HUMANITEC_TOKEN }} --org ${{ vars.HUMANITEC_ORG }} --app bank-demo --env development -f money-api/score.yaml --property containers.moneyapi.image=${{needs.build-moneyapi.outputs.IMAGE_NAME}}:${{needs.build-moneyapi.outputs.IMAGE_TAG}}
      
      - name: Run Score - Users API
        if: steps.changes.outputs.scorefiles == 'true'
        run: score-humanitec delta --retry --deploy --token ${{ secrets.HUMANITEC_TOKEN }} --org ${{ vars.HUMANITEC_ORG }} --app bank-demo --env development -f users-api/score.yaml --property containers.usersapi.image=${{needs.build-usersapi.outputs.IMAGE_NAME}}:${{needs.build-usersapi.outputs.IMAGE_TAG}}

      - name: Run Score - Frontend
        if: steps.changes.outputs.scorefiles == 'true'
        run: score-humanitec delta --retry --deploy --token ${{ secrets.HUMANITEC_TOKEN }} --org ${{ vars.HUMANITEC_ORG }} --app bank-demo --env development -f frontend/score.yaml --extensions frontend/humanitec.score.yaml --property containers.frontend.image=${{needs.build-frontend.outputs.IMAGE_NAME}}:${{needs.build-frontend.outputs.IMAGE_TAG}}
